### ISSUE TITLE
Control Details issue(In Flutter 2.8)

### ISSUE THREAD

**Issue by ShashankSMayya** [shang1219178163/enhance_stepper#3]
I have upgraded to flutter 2.8 and I am trying to build the project and I got the following issue.

 Error: The argument type 'SizedBox Function(BuildContext, {dynamic onStepCancel, dynamic onStepContinue})' can't be assigned to the parameter type 'Widget Function(BuildContext, ControlsDetails)'.
     - 'SizedBox' is from 'package:flutter/src/widgets/basic.dart' ('../../Development/flutter/packages/flutter/lib/src/widgets/basic.dart').
     - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../Development/flutter/packages/flutter/lib/src/widgets/framework.dart').
     - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('../../Development/flutter/packages/flutter/lib/src/widgets/framework.dart').
     - 'ControlsDetails' is from 'package:flutter/src/material/stepper.dart' ('../../Development/flutter/packages/flutter/lib/src/material/stepper.dart').
                controlsBuilder: (context, {onStepCancel, onStepContinue}) =>

And I tried to retype the controls builder and it gave me this as the method to type it.

controlsBuilder: (context,details) =>
                SizedBox.shrink(),

where the details are of type ControlsDetails

But then upon running again, I am getting 
Error: Too few positional arguments: 2 required, 1 given.
          return widget.controlsBuilder!(context,

**Comment by mi1971** [comment]
I'm getting the same as of 2.8

**Comment by shang1219178163** [comment]
fixed it.
